esphome:
  name: indoor-climate
  friendly_name: indoor-climate

esp8266:
  board: esp01_1m

i2c:
  - frequency: 100kHz

sensor:
  - platform: hdc1080
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "your-encryption-key"

ota:
  - platform: esphome
    password: "3e53d9f340a8c4abbd94fb6afd514d03"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .lan
  power_save_mode: HIGH # important to reduce self heating to avoid impact measurements

  ap:
    ssid: "Air Quality Sensor"
    password: "lcdporto"

web_server:
  port: 80

captive_portal:
    
